### ISSUE TITLE
Data-set deletion not working

### ISSUE THREAD

**Issue by bassoGeorge** [ChetanBhasin/Veracious#43]
@ChetanBhasin You might want to look into the deletion procedure.. it is not working really. Yes, the data-set gets deleted but it doesn't update the meta data properly and we still get those data-sets in the interface

**Comment by ChetanBhasin** [comment]
You already made the change by using a single context.

**Comment by ChetanBhasin** [comment]
Okay, but where on front end is the option to delete?

**Comment by ChetanBhasin** [comment]
Everything working fine now.
