### ISSUE TITLE
Spark Context error

### ISSUE THREAD

**Issue by bassoGeorge** [ChetanBhasin/Veracious#44]
@ChetanBhasin Cannot perform mining operations. Spark complaining that multiple spark contexts running in the JVM. I checked your code and saw that it is true. One is there in mlops and the other in that other package.. If it is your intent to run 2 contexts, then configure spark script to let you do so,

**Comment by ChetanBhasin** [comment]
You already solved the issue by using one instead of two spark contexts. That works.
